### ISSUE TITLE
Slow performance on Safari

### ISSUE THREAD

**Issue by SebDanielsson** [mistio/mist-ce#1005]
Hi! Just tried out Mist 4.4 via Linode Marketplace and it's really great. However the performance is a bit slow even though I only run 2 machines and have added 2 cloud providers. Also Safari displays the following message:
This web page is using significant memory. Closing it may improve the responsiveness of your Mac.

**Comment by cpsaltis** [comment]
Hi @SebDanielsson, what version of Safari are you running and on which OS version?

**Comment by SebDanielsson** [comment]
I'm running Safari 14 on macOS Big Sur on a MacBook Air M1 with 16 GB RAM.

**Comment by cpsaltis** [comment]
Hi @SebDanielsson, we haven't been able to reproduce this in any way. Did you notice slow performance only with Safari or other browsers as well? If it's amore general issue, the only thing I can think of is the size of the VM you used. If it's small there are probably delays due to the lack of resources. What's the size you are using?

**Comment by SebDanielsson** [comment]
Just read the system requirements for the server and saw that 4 cores is recommended. I used a VPS with 2 cores so that's probably why. Sorry about that.

BR
Sebastian

**Comment by cpsaltis** [comment]
No worries, I'm glad it wasn't another issue :) Just keep in mind that 4 cores and 4GB RAM is the minimum amount. I would recommend to double those depending on your usage.
