### ISSUE TITLE
LXD Images not refreshed

### ISSUE THREAD

**Issue by xaoc7** [mistio/mist-ce#1016]
Hello,
I'm using latest stable version of Mist-CE (4.5.5). I'm connecting an LXD cloud (LXD version 4.19.0). Problem is simple:
When I copy an LXD image (threw normal LXD commands ) that image is not available in already configured LXD cloud in Mist-CE UI.
In order to see and use the newly introduced image I need to at least log-off & logg-in again in the MistUI.

**Comment by d-mo** [comment]
Hi @xaoc7

Mist will poll your images every 30 minutes, since they usually don't change too often.

You can force a refresh by sending an HTTP GET request to `{portal_url}/api/v1/cloud/{cloud_id}/images` while logged in.

It's also possible to programmatically change the default polling interval for a specific cloud.

**Comment by xaoc7** [comment]
Awesome! Thanks for answering @d-mo
