### ISSUE TITLE
KVM on debian

### ISSUE THREAD

**Issue by almereyda** [mistio/mist-ce#886]
Even though I managed to replace `ubuntu-vm-builder` with https://github.com/josephbisch/vmbuilder and have extra installed `sudo cloud-utils uml-utilities genisoimage bridge-utils virt-viewer` on our debian virtualization host, Mist is only able to create the VMs meta-data file, but fails silently to build the `config.iso`, which is even successfully attached to the desired, then paused VM.

```
mist_1 | ==> var/log/uwsgi-stderr---supervisor-lVXgkq.log <==
mist_1 | 2016-10-05 22:25:53,376 INFO uWSGIWorker4Core0 methods - create_machine: Creating machine ecobytes-dokku on cloud 2M2EW5gknBQ8iPQouaiGrD8A5e5A
mist_1 | 2016-10-05 22:25:54,561 INFO Thread-21 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 
mist_1 | ==> var/log/sockjs-stderr---supervisor-dokXPH.log <==
mist_1 | 2016-10-05 22:25:54 INFO MainThread serve - heartbeat: 0 open connections in sockjs 8081
mist_1 | 
mist_1 | ==> var/log/uwsgi-stderr---supervisor-lVXgkq.log <==
mist_1 | 2016-10-05 22:25:54,893 INFO Thread-21 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:25:57,223 INFO Thread-23 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:25:57,545 INFO Thread-23 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:25:57,711 INFO Thread-25 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:25:58,034 INFO Thread-25 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:25:58,233 INFO Thread-27 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:25:58,558 INFO Thread-27 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:25:58,726 INFO Thread-29 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:25:59,056 INFO Thread-29 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:25:59,226 INFO Thread-31 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:25:59,553 INFO Thread-31 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:25:59,725 INFO Thread-33 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:26:00,052 INFO Thread-33 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:26:00,219 INFO Thread-35 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:26:00,541 INFO Thread-35 log - log: Authentication (publickey) successful!
mist_1 | 2016-10-05 22:26:04,393 INFO Thread-37 log - log: Connected (version 2.0, client OpenSSH_6.7p1)
mist_1 | 2016-10-05 22:26:04,725 INFO Thread-37 log - log: Authentication (publickey) successful!
mist_1 | libvir: Storage error : Cannot access storage file '/var/lib/libvirt/libcloud/ecobytes-dokku/config.iso' (as uid:109, gid:117): No such file or directory
mist_1 | 2016-10-05 22:26:06,620 INFO uWSGIWorker4Core0 views - exception_handler_mist: MistError: MachineCreationError("Machine creation failed: KVM, got exception Cannot access storage file '/var/lib/libvirt/libcloud/ecobytes-dokku/config.iso' (as uid:109, gid:117): No such file or directory",)
mist_1 | [pid: 226|app: 0|req: 15/33] 127.0.0.1 () {50 vars in 867 bytes} [Wed Oct  5 22:25:53 2016] POST /clouds/2M2EW5gknBQ8iPQouaiGrD8A5e5A/machines => generated 173 bytes in 13253 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
```

Though the domain is created

```
root@debian /var/lib/libvirt # ls libcloud/ecobytes-dokku/
meta-data
root@debian /var/lib/libvirt # virsh dominfo ecobytes-dokku
Id:             -
Name:           ecobytes-dokku
UUID:           0554fd03-042f-4b60-9176-b8ae9da41c76
OS Type:        hvm
State:          shut off
CPU(s):         4
Max memory:     4096000 KiB
Used memory:    0 KiB
Persistent:     yes
Autostart:      disable
Managed save:   no
Security model: none
Security DOI:   0

```

![bildschirmfoto vom 2016-10-06 00-36-25](https://cloud.githubusercontent.com/assets/1645308/19134224/11439d60-8b5d-11e6-854e-b6ca2bd173cd.png)

**Comment by mgogoulos** [comment]
Hi, 

you mention that genisoimage is already installed on the system, right?  What does dir /var/lib/libvirt/libcloud/ecobytes-dokku/ has after the machine creation failed?
Have a look on http://docs.mist.io/article/99-managing-kvm-with-mist-io , hope it helps

Regards

**Comment by almereyda** [comment]
No, the docs don't help.

To paste the output from above again:

```
root@debian /var/lib/libvirt # ls libcloud/ecobytes-dokku/
meta-data
```

Thanks.

**Comment by mgogoulos** [comment]
given the fact that it has received an .img image file, a path to create a disk, ssh key and cloudinit, and a VM name "ecobytes-dokku", it will:

1) create dir /var/lib/libvirt/libcloud/ecobytes-dokku
2) create file /var/lib/libvirt/libcloud/ecobytes-dokku/meta-data with name+public key info
3) create file /var/lib/libvirt/libcloud/ecobytes-dokku/user-data with the cloudinit file contents
4) create file /var/lib/libvirt/libcloud/ecobytes-dokku/config.iso which will be the output of command
`sudo genisoimage -o /var/lib/libvirt/libcloud/ecobytes-dokku/config.iso -V cidata -r -J /var/lib/libvirt/libcloud/ecobytes-dokku/user-data /var/lib/libvirt/libcloud/ecobytes-dokku/meta-data
5) start the VM with the disk /var/lib/libvirt/disks/ecobytes.img and cd-rom /var/lib/libvirt/libcloud/ecobytes-dokku/config.iso , so that the first time it boots it boots with the .iso file, and after that it boots with the disk image


It seems in your case that only 1+2 have worked, where 3+4 have failed (and of course 5 fails since it can't find a cd-rom disk to boot). Since commands 2 and 3 are the same (output the contents of a file to another one) seems that the cloud_init is not parsed correctly and the file cannot be created. A first guess is that the double quotes on the cloudinit code create the problem. 

We will have to look why this happens,  thank you very much for reporting

**Comment by almereyda** [comment]
So I could just try again [with different quoting styles](http://stackoverflow.com/a/22235064/1959568) in the YAML.
