### ISSUE TITLE
Adding SSH Key - Private key is not a valid RSA key

### ISSUE THREAD

**Issue by ruskofd** [mistio/mist-ce#943]
Hi !

I try to add my SSH keys to Mist.io (but uploading my id_rsa file), but there is a problem during adding it.

`Bad Request: {'msg': u"ValidationError (Key.SSHKey:de744eb14653461c82d0263f01537c67) (Private key is not a valid RSA key.: ['__all__'] Field is required: ['public'])", 'errors': {'public': u'Field is required', '__all__': u'Private key is not a valid RSA key.'}}`

I generate my SSH key using the following command line : `ssh-keygen -t rsa -b 4096`.

![image](https://user-images.githubusercontent.com/19529621/49343750-45f09e80-f66f-11e8-8175-4c63d5a53276.png)

This should be fine no ?

Thanks you.

**Release version :**
v3.3.0 and v3.3.1

**System**
Fedora 29
Docker version : Nightly

**Comment by RuskofFR** [comment]
I tried with on a CentOS 7.5 (1804) VM, it works nicely. Ok thanks for the response.

**Comment by kaanklky** [comment]
Hi @d-mo,
I added my GCE project to Mist.io but I can't add GCE service's SSH key to keys because of same error. Are there any release date or workaround for fix of this issue?

**Release version:**
v4.0.3

![Screenshot_2019-04-11_20-25-02](https://user-images.githubusercontent.com/4572033/56026774-8cd95980-5d1d-11e9-9da6-81757e0e5f1c.png)

**Comment by d-mo** [comment]
Thank you @kaanklky for reminding us of this issue. I'll make sure it's fixed in v4.1 which should be out in the coming weeks.

**Comment by d-mo** [comment]
@ruskofd @kaanklky Support for the new OpenSSH key format was added in [v4.1.0](https://github.com/mistio/mist-ce/releases/tag/v4.1.0)
