### ISSUE TITLE
Mist IO graphs are not populating 

### ISSUE THREAD

**Issue by ssullivan98** [mistio/mist-ce#990]
Ive enabled monitoring on multiple hosts but the graphs for each host are not populating with any information, im able to connect via shell so my associated key should work fine 

![image](https://user-images.githubusercontent.com/35775299/93789895-6c931700-fc00-11ea-890f-7f026e94d15e.png)

**Comment by dmeniche** [comment]
You have to modify the telegraf variables configuration file to make it point to the influxdb container at port 8086

**Comment by d-mo** [comment]
Actually you shouldn't change the telegraf configuration in this way. There are a couple other components in front of the influx container.

Have you configured CORE_URI in settings.py as described in the README https://github.com/mistio/mist-ce/blob/master/README.md#required-configuration

It needs to be addressable by the monitored machines in order to see graphs.

**Comment by ssullivan98** [comment]
> 
> 
> Actually you shouldn't change the telegraf configuration in this way. There are a couple other components in front of the influx container.
> 
> Have you configured CORE_URI in settings.py as described in the README https://github.com/mistio/mist-ce/blob/master/README.md#required-configuration
> 
> It needs to be addressable by the monitored machines in order to see graphs.

Sorry I forgot to close this out, I resolved the issue already
