### ISSUE TITLE
  integrate Hetzner Cloud?

### ISSUE THREAD

**Issue by ALutz273** [mistio/mist-ce#996]
Is it possible to integrate the Cloud Provider Hetzner? 
This also very well documented but I am not a good programmer. But I could do the testing

[https://github.com/hetznercloud/awesome-hcloud ](https://github.com/hetznercloud/awesome-hcloud)

**Comment by cpsaltis** [comment]
Hi @ALutz273, we've been considering this for some time now but we never really got around to it. Are you using just their cloud servers or also the dedicated ones?

**Comment by ALutz273** [comment]
I only use the cloud server service from hetzner.

**Comment by sebastianberm** [comment]
@cpsaltis : What would you need to help get this on the road?
(For both bare metal and cloud ;-))

**Comment by cpsaltis** [comment]
Hi @sebastianberm,

We are a little hesitant to add support for new clouds because besides the initial development effort there is considerable ongoing maintenance involved. For this reason we usually do it when (a) there is a request from a paying customer, or (b) there is a community member willing to do the integration and maintenance work. Obviously we'd be more than happy to assist in the case of (b).

You can reach out to me directly at cpsaltis at mist.io if you'd like to discuss further.
